import LegalPage, { COMPANY } from "../../components/LegalPage";

const SITE_URL = "https://grahaisystems.com";

export const metadata = {
  title: "Terms & Conditions | GrahAI Systems",
  description:
    "Terms and Conditions governing the use of GrahAI Systems' website and AI engineering services.",
  alternates: { canonical: `${SITE_URL}/terms` },
};

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms & Conditions"
      updated="June 30, 2026"
      intro={`These Terms & Conditions ("Terms") govern your use of the ${COMPANY.name} website (grahaisystems.com) and the AI design, engineering and consulting services we provide. By using our website, requesting a quote, or engaging our services, you agree to these Terms.`}
      sections={[
        {
          heading: "1. Who we are",
          paragraphs: [
            `${COMPANY.name} is an AI software studio based in ${COMPANY.addressLine}. We design, build and operate production-grade AI systems and deliver AI engineering services to clients in India and worldwide.`,
          ],
        },
        {
          heading: "2. Quotes and scope",
          paragraphs: [
            `Prices, timelines and scope shown on this website — including any quote generated by our AI Solutions Architect — are <strong>indicative estimates</strong> based on the information you provide. They are not a binding offer. A final scope, price and timeline are confirmed in writing after a discovery call and recorded in an engagement agreement or order confirmation.`,
          ],
        },
        {
          heading: "3. Payments",
          list: [
            `Payments are processed securely by our payment partner, <strong>Razorpay</strong>. We do not store your card or banking details.`,
            `For larger engagements, the amount payable online is a <strong>booking deposit</strong> that reserves your delivery slot and is credited in full toward the project. Smaller productized packages may be payable in full.`,
            `Prices are shown in INR for customers in India and in USD for international customers. Applicable taxes (e.g. GST) may be added where required by law.`,
            `The remaining project balance (if any) is invoiced per the milestones in your engagement agreement.`,
          ],
        },
        {
          heading: "4. Delivery",
          paragraphs: [
            `Our services are delivered digitally (software, code, documentation, access and reports) over email and online tools. Indicative delivery timelines are stated per engagement; the agreed timeline is confirmed in your engagement agreement. See our <a href="/shipping" class="text-azure-600 font-semibold">Delivery Policy</a>.`,
          ],
        },
        {
          heading: "5. Intellectual property",
          paragraphs: [
            `Unless otherwise agreed in writing, on full payment for an engagement you receive ownership or a license to the deliverables produced specifically for you. ${COMPANY.name} retains ownership of its pre-existing tools, frameworks, and know-how used to build them.`,
          ],
        },
        {
          heading: "6. Acceptable use",
          paragraphs: [
            `You agree not to use our website or services to violate any law, infringe third-party rights, or submit content you do not have the right to share. We may decline or end engagements that are unlawful, unsafe, or outside our capability.`,
          ],
        },
        {
          heading: "7. Confidentiality",
          paragraphs: [
            `We treat the project details you share with us as confidential and use them only to scope, quote and deliver your engagement. See our <a href="/privacy" class="text-azure-600 font-semibold">Privacy Policy</a>.`,
          ],
        },
        {
          heading: "8. Warranties and liability",
          paragraphs: [
            `We deliver services with reasonable skill and care. To the maximum extent permitted by law, ${COMPANY.name} is not liable for indirect or consequential losses, and our total liability for any engagement is limited to the fees paid for that engagement. AI systems are probabilistic; we do not warrant that any model output is error-free.`,
          ],
        },
        {
          heading: "9. Cancellation and refunds",
          paragraphs: [
            `Cancellations and refunds are governed by our <a href="/refund" class="text-azure-600 font-semibold">Cancellation & Refund Policy</a>.`,
          ],
        },
        {
          heading: "10. Governing law",
          paragraphs: [
            `These Terms are governed by the laws of India, and the courts at Bengaluru, Karnataka have exclusive jurisdiction over any dispute.`,
          ],
        },
        {
          heading: "11. Changes",
          paragraphs: [
            `We may update these Terms from time to time. The current version is always available at grahaisystems.com/terms.`,
          ],
        },
      ]}
    />
  );
}
